/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author kdani
 */
public class AgregarLibro extends javax.swing.JFrame {

    /**
     * Creates new form AgregarLibro
     */
    public AgregarLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarL = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        txfNomLibro = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();
        labNomLibro = new javax.swing.JLabel();
        Regresar3 = new javax.swing.JButton();
        txfNomAutor = new javax.swing.JTextField();
        labNomAutor = new javax.swing.JLabel();
        txfEditorial = new javax.swing.JTextField();
        labEditorial = new javax.swing.JLabel();
        txfId = new javax.swing.JTextField();
        labClave = new javax.swing.JLabel();
        txfCat = new javax.swing.JTextField();
        labCant = new javax.swing.JLabel();
        agregarlibro = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        labCat = new javax.swing.JLabel();
        txfCantidad = new javax.swing.JTextField();

        setAlwaysOnTop(true);

        panelAgregarL.setBackground(new java.awt.Color(255, 255, 255));
        panelAgregarL.setBorder(javax.swing.BorderFactory.createMatteBorder(8, 8, 8, 8, new java.awt.Color(0, 204, 204)));

        titulo1.setFont(new java.awt.Font("Brand New Retro", 0, 60)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 204, 204));
        titulo1.setText("El ARTE ");

        titulo2.setFont(new java.awt.Font("KG Starting Over", 1, 36)); // NOI18N
        titulo2.setForeground(new java.awt.Color(0, 204, 204));
        titulo2.setText("de leer");

        txfNomLibro.setToolTipText("Titulo del LIbro");

        actualizar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        actualizar.setForeground(new java.awt.Color(0, 204, 204));
        actualizar.setText("Actualizar");
        actualizar.setToolTipText("Actualizar libro");

        labNomLibro.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        labNomLibro.setForeground(new java.awt.Color(0, 204, 204));
        labNomLibro.setText("Libro:");

        Regresar3.setBackground(new java.awt.Color(0, 204, 204));
        Regresar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_BibliotecaListo2.png"))); // NOI18N
        Regresar3.setToolTipText("Regresar al inicio");

        txfNomAutor.setToolTipText("Nombre del autor");

        labNomAutor.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        labNomAutor.setForeground(new java.awt.Color(0, 204, 204));
        labNomAutor.setText("Autor:");

        txfEditorial.setToolTipText("Nombre de la editorial");

        labEditorial.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        labEditorial.setForeground(new java.awt.Color(0, 204, 204));
        labEditorial.setText("Editorial:");

        txfId.setToolTipText("ID del Libro");

        labClave.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        labClave.setForeground(new java.awt.Color(0, 204, 204));
        labClave.setText("Clave:");

        txfCat.setToolTipText("Categoria del Libro");

        labCant.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        labCant.setForeground(new java.awt.Color(0, 204, 204));
        labCant.setText("Cantidad:");

        agregarlibro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        agregarlibro.setForeground(new java.awt.Color(0, 204, 204));
        agregarlibro.setText("Agregar");
        agregarlibro.setToolTipText("Agregar un Libro");

        buscar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 204, 204));
        buscar.setText("Buscar");
        buscar.setToolTipText("Buscar libro");

        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        eliminar.setForeground(new java.awt.Color(0, 204, 204));
        eliminar.setText("Eliminar");
        eliminar.setToolTipText("Eliminar libro");

        labCat.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        labCat.setForeground(new java.awt.Color(0, 204, 204));
        labCat.setText("Categoria:");

        txfCantidad.setToolTipText("Ingrese la cantidad de libros");

        javax.swing.GroupLayout panelAgregarLLayout = new javax.swing.GroupLayout(panelAgregarL);
        panelAgregarL.setLayout(panelAgregarLLayout);
        panelAgregarLLayout.setHorizontalGroup(
            panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarLLayout.createSequentialGroup()
                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgregarLLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Regresar3))
                    .addGroup(panelAgregarLLayout.createSequentialGroup()
                        .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarLLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelAgregarLLayout.createSequentialGroup()
                                        .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labEditorial)
                                            .addGroup(panelAgregarLLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labNomAutor)
                                                    .addComponent(labNomLibro))))
                                        .addGap(12, 12, 12)
                                        .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txfNomAutor, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txfEditorial)
                                            .addComponent(txfNomLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(agregarlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelAgregarLLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelAgregarLLayout.createSequentialGroup()
                                        .addComponent(labCant)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelAgregarLLayout.createSequentialGroup()
                                        .addComponent(labCat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfCat, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelAgregarLLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelAgregarLLayout.createSequentialGroup()
                                        .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33))
                                    .addGroup(panelAgregarLLayout.createSequentialGroup()
                                        .addComponent(labClave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        panelAgregarLLayout.setVerticalGroup(
            panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(titulo2))
                    .addComponent(Regresar3))
                .addGap(23, 23, 23)
                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labClave)
                    .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgregarLLayout.createSequentialGroup()
                        .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNomLibro)
                            .addComponent(txfNomLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNomAutor)
                            .addComponent(txfNomAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labEditorial)
                            .addComponent(txfEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCat))
                        .addGap(29, 29, 29))
                    .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labCant)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(panelAgregarLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizar)
                    .addComponent(agregarlibro)
                    .addComponent(buscar)
                    .addComponent(eliminar))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAgregarL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAgregarL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Regresar3;
    public javax.swing.JButton actualizar;
    public javax.swing.JButton agregarlibro;
    public javax.swing.JButton buscar;
    public javax.swing.JButton eliminar;
    public javax.swing.JLabel labCant;
    public javax.swing.JLabel labCat;
    public javax.swing.JLabel labClave;
    public javax.swing.JLabel labEditorial;
    public javax.swing.JLabel labNomAutor;
    public javax.swing.JLabel labNomLibro;
    public javax.swing.JPanel panelAgregarL;
    public javax.swing.JLabel titulo1;
    public javax.swing.JLabel titulo2;
    public javax.swing.JTextField txfCantidad;
    public javax.swing.JTextField txfCat;
    public javax.swing.JTextField txfEditorial;
    public javax.swing.JTextField txfId;
    public javax.swing.JTextField txfNomAutor;
    public javax.swing.JTextField txfNomLibro;
    // End of variables declaration//GEN-END:variables
}
