/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author kdani
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_login = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        logo_login = new javax.swing.JLabel();
        crearUsuario = new javax.swing.JButton();
        ingresar_login = new javax.swing.JButton();
        labUusario_login = new javax.swing.JLabel();
        labContra_login = new javax.swing.JLabel();
        txfUsuario_login = new javax.swing.JTextField();
        txfContra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_login.setBackground(new java.awt.Color(0, 204, 204));
        panel_login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titulo2.setFont(new java.awt.Font("KG Starting Over", 1, 36)); // NOI18N
        titulo2.setText("de leer");

        titulo.setFont(new java.awt.Font("Brand New Retro", 0, 60)); // NOI18N
        titulo.setText("El ARTE ");

        logo_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_BibliotecaListo.png"))); // NOI18N

        crearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        crearUsuario.setText("Nuevo");
        crearUsuario.setToolTipText("Crear Nuevo Usuario");

        ingresar_login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ingresar_login.setText("Ingresar");
        ingresar_login.setToolTipText("Ingresar al menu Principal");
        ingresar_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresar_loginActionPerformed(evt);
            }
        });

        labUusario_login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labUusario_login.setText("Nombre de Usuario");

        labContra_login.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labContra_login.setText("Contraseña");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(crearUsuario)
                                .addGap(34, 34, 34)
                                .addComponent(ingresar_login))
                            .addGroup(panel_loginLayout.createSequentialGroup()
                                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfUsuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_loginLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(labContra_login))
                                    .addGroup(panel_loginLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(labUusario_login)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txfContra))
                        .addGap(18, 18, 18)
                        .addComponent(logo_login, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addComponent(titulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titulo2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(titulo2))
                .addGap(32, 32, 32)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addComponent(labUusario_login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfUsuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labContra_login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txfContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearUsuario)
                            .addComponent(ingresar_login)))
                    .addComponent(logo_login, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(468, 468, 468))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresar_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresar_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresar_loginActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton crearUsuario;
    public javax.swing.JButton ingresar_login;
    public javax.swing.JLabel labContra_login;
    public javax.swing.JLabel labUusario_login;
    public javax.swing.JLabel logo_login;
    public javax.swing.JPanel panel_login;
    public javax.swing.JLabel titulo;
    public javax.swing.JLabel titulo2;
    public javax.swing.JPasswordField txfContra;
    public javax.swing.JTextField txfUsuario_login;
    // End of variables declaration//GEN-END:variables
}
